//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSW1_ELF_Alave.ReferenciaNegocios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdpaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idpais {
            get {
                return this.IdpaisField;
            }
            set {
                if ((object.ReferenceEquals(this.IdpaisField, value) != true)) {
                    this.IdpaisField = value;
                    this.RaisePropertyChanged("Idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCia {
            get {
                return this.NombreCiaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCiaField, value) != true)) {
                    this.NombreCiaField = value;
                    this.RaisePropertyChanged("NombreCia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pais", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Pais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPaisField, value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePais {
            get {
                return this.NombrePaisField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePaisField, value) != true)) {
                    this.NombrePaisField = value;
                    this.RaisePropertyChanged("NombrePais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedidoscabe", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Pedidoscabe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clientepedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empleadoPedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionDestinatario {
            get {
                return this.DireccionDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionDestinatarioField, value) != true)) {
                    this.DireccionDestinatarioField = value;
                    this.RaisePropertyChanged("DireccionDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPedido {
            get {
                return this.FechaPedidoField;
            }
            set {
                if ((this.FechaPedidoField.Equals(value) != true)) {
                    this.FechaPedidoField = value;
                    this.RaisePropertyChanged("FechaPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientepedido {
            get {
                return this.clientepedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.clientepedidoField, value) != true)) {
                    this.clientepedidoField = value;
                    this.RaisePropertyChanged("clientepedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empleadoPedido {
            get {
                return this.empleadoPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.empleadoPedidoField, value) != true)) {
                    this.empleadoPedidoField = value;
                    this.RaisePropertyChanged("empleadoPedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaNegocios.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Clientes", ReplyAction="http://tempuri.org/IService1/ClientesResponse")]
        DSW1_ELF_Alave.ReferenciaNegocios.Cliente[] Clientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Clientes", ReplyAction="http://tempuri.org/IService1/ClientesResponse")]
        System.Threading.Tasks.Task<DSW1_ELF_Alave.ReferenciaNegocios.Cliente[]> ClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Paises", ReplyAction="http://tempuri.org/IService1/PaisesResponse")]
        DSW1_ELF_Alave.ReferenciaNegocios.Pais[] Paises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Paises", ReplyAction="http://tempuri.org/IService1/PaisesResponse")]
        System.Threading.Tasks.Task<DSW1_ELF_Alave.ReferenciaNegocios.Pais[]> PaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pedidoscabexyear", ReplyAction="http://tempuri.org/IService1/PedidoscabexyearResponse")]
        DSW1_ELF_Alave.ReferenciaNegocios.Pedidoscabe[] Pedidoscabexyear(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pedidoscabexyear", ReplyAction="http://tempuri.org/IService1/PedidoscabexyearResponse")]
        System.Threading.Tasks.Task<DSW1_ELF_Alave.ReferenciaNegocios.Pedidoscabe[]> PedidoscabexyearAsync(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pedidoscabexcliente", ReplyAction="http://tempuri.org/IService1/PedidoscabexclienteResponse")]
        DSW1_ELF_Alave.ReferenciaNegocios.Pedidoscabe[] Pedidoscabexcliente(string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pedidoscabexcliente", ReplyAction="http://tempuri.org/IService1/PedidoscabexclienteResponse")]
        System.Threading.Tasks.Task<DSW1_ELF_Alave.ReferenciaNegocios.Pedidoscabe[]> PedidoscabexclienteAsync(string cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DSW1_ELF_Alave.ReferenciaNegocios.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DSW1_ELF_Alave.ReferenciaNegocios.IService1>, DSW1_ELF_Alave.ReferenciaNegocios.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DSW1_ELF_Alave.ReferenciaNegocios.Cliente[] Clientes() {
            return base.Channel.Clientes();
        }
        
        public System.Threading.Tasks.Task<DSW1_ELF_Alave.ReferenciaNegocios.Cliente[]> ClientesAsync() {
            return base.Channel.ClientesAsync();
        }
        
        public DSW1_ELF_Alave.ReferenciaNegocios.Pais[] Paises() {
            return base.Channel.Paises();
        }
        
        public System.Threading.Tasks.Task<DSW1_ELF_Alave.ReferenciaNegocios.Pais[]> PaisesAsync() {
            return base.Channel.PaisesAsync();
        }
        
        public DSW1_ELF_Alave.ReferenciaNegocios.Pedidoscabe[] Pedidoscabexyear(int y) {
            return base.Channel.Pedidoscabexyear(y);
        }
        
        public System.Threading.Tasks.Task<DSW1_ELF_Alave.ReferenciaNegocios.Pedidoscabe[]> PedidoscabexyearAsync(int y) {
            return base.Channel.PedidoscabexyearAsync(y);
        }
        
        public DSW1_ELF_Alave.ReferenciaNegocios.Pedidoscabe[] Pedidoscabexcliente(string cliente) {
            return base.Channel.Pedidoscabexcliente(cliente);
        }
        
        public System.Threading.Tasks.Task<DSW1_ELF_Alave.ReferenciaNegocios.Pedidoscabe[]> PedidoscabexclienteAsync(string cliente) {
            return base.Channel.PedidoscabexclienteAsync(cliente);
        }
    }
}
